// Task E — RF-O831 conformance by VM execution, not by mock.
//
// The 0.4.0 identity vault adds `require(this.age >= 144)` to burn().
// CashScript compiles `this.age >= N` to a CHECKSEQUENCEVERIFY over the
// input's nSequence (relative locktime), so the binding depends on the
// sequence the spending transaction declares:
//
//   sequence 143 (CSV enforced, age < 144) -> the VM rejects the spend
//   sequence 144 (CSV enforced, age = 144) -> the VM accepts the spend
//   sequence with the CSV disable flag set (e.g. 0xfffffffe, the default
//                          every ordinary wallet uses) -> CSV passes, so the
//                          delay does NOT bind that spend
//
// The last row is a finding, not an assumption: libauth's `opCheckSequenceVerify`
// (BCH_2026_05) fails with `unmatchedSequenceDisable` when the input's nSequence
// sets the CSV disable flag (bit 31), and fails again on a seconds-unit sequence
// and on any mask below 144. The delay is therefore a HARD constraint of the
// VM: a burn transaction MUST declare a relative-lock sequence in block units
// with a masked value of at least 144, and a wallet that signs with the default
// disabled sequence signs an invalid transaction. The conformance tests here
// assert exactly what the VM does for each class of spend and record the
// full matrix in C-CONFORMIDAD.
//
// Evaluation vehicle: cashscript 0.13.2 `TransactionBuilder.debug()`, which
// runs the transaction through libauth's Bitcoin Cash Virtual Machine at the
// current consensus target (BCH_2026_05), with the real compiled bytecode and
// a signature generated by the scenario engine. This is not a mock provider:
// the mock is used only as an in-memory UTXO ledger, the script evaluation is
// the real VM.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { secp256k1, binToHex } from '@bitauth/libauth';
import {
  Contract,
  MockNetworkProvider,
  SignatureAlgorithm,
  SignatureTemplate,
  TransactionBuilder,
} from 'cashscript';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const artifact = JSON.parse(
  readFileSync(join(root, 'artifacts', 'identity_vault_0_4_0.json'), 'utf8'),
);
const constants = JSON.parse(
  readFileSync(join(root, 'protocol', 'constants.json'), 'utf8'),
);
const bytecode = JSON.parse(
  readFileSync(join(root, 'protocol', 'covenant-bytecode.json'), 'utf8'),
);

// Deterministic test key controlled by the test, nothing real.
const privateKey = Uint8Array.from({ length: 32 }, (_, i) => i + 1);
const publicKey = secp256k1.derivePublicKeyCompressed(privateKey);
const hash160 = (bytes) =>
  createHash('ripemd160').update(createHash('sha256').update(bytes).digest()).digest();
const ownerPkh = hash160(publicKey);

// P2PKH locking bytecode for the owner (the burn covenant re-locks everything
// to the owner, output 0 and output 1).
const ownerLock = new Uint8Array([
  0x76, 0xa9, 0x14, ...ownerPkh, 0x88, 0xac,
]);

const provider = new MockNetworkProvider();
const contract = new Contract(artifact, [ownerPkh], { provider });
const sigTemplate = new SignatureTemplate(privateKey, undefined, SignatureAlgorithm.ECDSA);
const unlocker = contract.unlock.burn(sigTemplate.getPublicKey(), sigTemplate);

// A funded vault UTXO: an NFT (commitment = ownerPkh) locked under the
// covenant with 5000 sats of collateral. Its genesis tx is not part of the
// test: the body under test is the burn spend, everything before it is
// presupposed.
const vault = {
  txid: 'ab'.repeat(32),
  vout: 0,
  satoshis: 5000n,
  token: {
    amount: 0n,
    category: 'cd'.repeat(32),
    nft: { capability: 'none', commitment: binToHex(ownerPkh) },
  },
};

// Builds, signs and VM-evaluates a burn spend whose single input declares the
// given nSequence. Returns { hex, debugCount } on success, throws on VM reject.
function evaluateBurn(sequence) {
  const builder = new TransactionBuilder({ provider, maximumFeeSatoshis: 2000n });
  builder.addInput(vault, unlocker, { sequence });
  builder.addOutput({ to: ownerLock, amount: 3000n });
  builder.addOutput({ to: ownerLock, amount: 1000n });
  const hex = builder.build();
  const results = builder.debug();
  return { hex, results };
}

test('the compiled 0.4.0 body contains the burn delay as a CHECKSEQUENCEVERIFY of 144', () => {
  // cashc compiles `this.age >= 144` to: push 144 (`02 90 00`, little endian),
  // OP_CHECKSEQUENCEVERIFY (`b2`), OP_DROP (`75`).
  const v040 = bytecode.contracts.identityVault.versions['0.4.0'];
  const v030 = bytecode.contracts.identityVault.versions['0.3.0'];
  assert.ok(v040.bytecodeHex.includes('029000b2'), '0.4.0 must push 144 then OP_CSV');
  assert.ok(
    constants.identityVault.minBurnDelayBlocks === 144,
    'the 144 in the bytecode must match constants.identityVault.minBurnDelayBlocks',
  );
  assert.ok(
    !v030.bytecodeHex.includes('029000b2'),
    '0.3.0 (frozen) must not contain the delay',
  );
});

// Throws the evaluated error from a rejected burn for message assertions.
function rejectBurn(sequence) {
  try {
    evaluateBurn(sequence);
  } catch (error) {
    return String(error?.message ?? error);
  }
  assert.fail(`expected the VM to reject sequence ${sequence}`);
  return '';
}

test('VM rejects a burn at age 143 (sequence lock enforced, below 144)', () => {
  const message = rejectBurn(143);
  assert.match(message, /require\(this\.age >= 144\)/, 'must report the failing burn-delay statement');
});

test('VM accepts a burn at age 144 (sequence lock enforced, at the threshold)', () => {
  const { results } = evaluateBurn(144);
  assert.ok(results, 'debug() must return a trace for an accepted burn');
});

test('VM accepts a burn at age 145 (above the threshold)', () => {
  assert.ok(evaluateBurn(145).results, 'age above 144 must be spendable');
});

test('the disable flag does NOT bypass the delay: the VM rejects it', () => {
  // Empirically verified against libauth's Bitcoin Cash Virtual Machine
  // (BCH_2026_05): `opCheckSequenceVerify` fails with
  // `unmatchedSequenceDisable` when the INPUT's nSequence has the CSV
  // disable flag (bit 31) set. There is no BIP112-style "disabled sequence
  // skips the check" here: 0xfffffffe (the sequence every ordinary
  // CashScript spend uses by default) is REJECTED. The delay cannot be
  // evaded by disabling the lock; a burn tx MUST declare a relative-lock
  // sequence (bit 31 clear) whose masked value is at least 144.
  const error = rejectBurn(0xfffffffe);
  assert.match(error, /require\(this\.age >= 144\)/);
});

test('a seconds-unit sequence does not satisfy the block-unit delay', () => {
  // 0x00400090 has the type flag (seconds) set; the compiled `require`
  // pushes 144 in block units. The VM reports an incompatible type and
  // rejects the burn.
  const error = rejectBurn(0x00400090);
  assert.match(error, /require\(this\.age >= 144\)/);
});